version: "3.8"

services:
  spring:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee_creator
      SPRING_DATASOURCE_USERNAME: root
    command: sh -c 'sleep 15 && java -jar /app/employee-creator.jar'
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: employee_creator
      MYSQL_USER: root
    ports:
      - "3307:3306"
    volumes:
      - ./database/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
