name: Java Spring Boot Tests with Maven

on: [push]

jobs:
  test:
    name: JUnit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: employee_creator
          MYSQL_USERNAME: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_HOST: mysql
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3.2.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Tests
        run: mvn -B test --file pom.xml
