env:
  TEST_DB_URL: jdbc:h2://mem:db;DB_CLOSE_DELAY=-1
  MYSQL_HOST: localhost

name: Java Spring Boot Tests with Maven

on: [push]

jobs:
  test:
    name: JUnit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: employee_creator
          MYSQL_USERNAME: root
          # MYSQL_ROOT_PASSWORD: password
          MYSQL_HOST: mysql
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost"

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3.2.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Print environment variables
        run: echo "****** $TEST_DB_URL ****** ${{secrets.MYSQL_HOST}} ++++++"

      - name: Run Tests
        run: mvn -B test --file pom.xml
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306]}}
