name: Java Spring Boot Tests with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven packages
        uses: actions/cache@v2
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
