name: Java Spring Boot Tests with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 17
          
      - name: Cache Maven packages
        uses: actions/cache@v2
          
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
