name: Java Spring Boot Tests with Maven

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Maven
      uses: stCarolas/setup-maven@4.5 

    - name: Run Tests
      run: mvn clean install
